version: '3'
services:
  db:
    container_name: postgres_db
    image: postgres:13.3-alpine
    ports:
      - "${PGADMIN_PORT:-5432}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_NAME}
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      timeout: 20s
      retries: 10
  web:
    container_name: django_server
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
      mailhog:
        condition: service_started
      
  mailhog:
    image: mailhog/mailhog
    ports:
      - '19802:8025'
volumes:
  postgresql_data: