# Generated by Django 4.2.1 on 2023-10-11 16:08

import companies_site.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterField(
            model_name='company',
            name='profile_file',
            field=models.FileField(storage=companies_site.storage_backends.PrivateMediaStorage(), upload_to='company_profiles/'),
        ),
    ]
